version: '2'

networks:
  app-tier:
    driver: bridge

services:
  minio-0:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data_0:/data-0'
      - 'minio_mnt_0:/data-1'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
  #     - MINIO_DISTRIBUTED_MODE_ENABLED=yes
  #     - MINIO_DISTRIBUTED_NODES=minio-{0...1}/data-{0...1}
  #     - MINIO_SKIP_CLIENT=yes
  # minio-1:
  #   image: docker.io/bitnami/minio:2022
  #   ports:
  #     - '9002:9000'
  #     - '9003:9001'
  #   volumes:
  #     - 'minio_mnt_0:/data-0'
  #     - 'minio_mnt_1:/data-1'
  #   environment:
  #     - MINIO_ACCESS_KEY=minio-access-key
  #     - MINIO_SECRET_KEY=minio-secret-key
  #     - MINIO_DISTRIBUTED_MODE_ENABLED=yes
  #     - MINIO_DISTRIBUTED_NODES=minio-{0...1}/data-{0...1}
  #     - MINIO_SKIP_CLIENT=yes
  ml-workspace:
    #build: .build
    image: mltooling/ml-workspace-gpu:0.13.2
    ports:
      - 8849:8080
    volumes:
      - workspace:/workspace
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1600000000 # ~16gb
    restart: always

volumes:
  workspace:
    driver: local
  minio_data_0:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/minio/1
  minio_mnt_0:
    external: true
  # minio_mnt_1:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /mnt/minio/2

