version: '3'

services:
  minio-0:
    image: chezhipower/minio:gateway
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_mnt_0:/data
      - minio_data_0:/mnt/cache
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminkey
      - MINIO_CACHE="on"
      - MINIO_CACHE_DRIVES=/mnt/cache
      - MINIO_CACHE_EXCLUDE=" "
      - MINIO_CACHE_QUOTA=80
      - MINIO_CACHE_AFTER=0
      - MINIO_CACHE_WATERMARK_LOW=70
      - MINIO_CACHE_WATERMARK_HIGH=90
    #command: ["${RUNFILE}"]
    command: gateway nas /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio-1:
    image: chezhipower/minio:gateway
    ports:
      - '9002:9000'
      - '9003:9001'
    volumes:
      - minio_mnt_1:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminkey
      - MINIO_CACHE="off"
    command: gateway nas /data --console-address ":9003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio-2:
    image: bitnami/minio:2022
    ports:
      - '9004:9000'
      - '9005:9001'
    volumes:
      - minio_data_1:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminkey
    #command: server /data --console-address ":9003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  ml-workspace:
    #build: .build
    image: mltooling/ml-workspace:0.13.2
    ports:
      - 8849:8080
    volumes:
      - /home/elan/devenv/minio-manager/workspace:/workspace
      - /home/dockeruser/shared-DVC-cache:/dvc-cache
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 800000000 # ~16gb
    restart: always

volumes:
  workspace:
    driver: local
  minio_data_0:          # Cache Drive to SSD /data/minio/1
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/minio/1
  minio_data_1:          # Cache Drive to SSD /data/minio/2
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/minio/2
  minio_mnt_0:          # RDS6 Remote share, docker volume already created using create_docker_volume.sh
    external: true
  minio_mnt_1:
    external: true
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /mnt/minio/2

