version: '3'

services:
  minio-0:
    image: chezhipower/minio:gateway
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_mnt_p:/data
      - minio_data_p:/mnt/cache
    environment:
      - MINIO_ROOT_USER=$ELANUSR
      - MINIO_ROOT_PASSWORD=$ELANPWD
      - MINIO_CACHE="on"
      - MINIO_CACHE_DRIVES=/mnt/cache
      - MINIO_CACHE_EXCLUDE=" "
      - MINIO_CACHE_QUOTA=90
      - MINIO_CACHE_AFTER=3
      - MINIO_CACHE_WATERMARK_LOW=70
      - MINIO_CACHE_WATERMARK_HIGH=95
    #command: ["${RUNFILE}"]
    command: gateway nas /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  ml-workspace-elan:
    #build: .build
    image: chezhipower/ml-workspace-devenv1:0
    ports:
      - 8849:8080
    volumes:
      - /home/elan/ml-workspace:/workspace
      - /home/dockeruser/shared-DVC-cache:/dvc-cache
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 800000000 # ~16gb
    environment:
      - AUTHENTICATE_VIA_JUPYTER=$ELANPWD 
    restart: always
  ml-workspace-ike:
    #build: .build
    image: chezhipower/ml-workspace-devenv1:0
    ports:
      - 8850:8080
    volumes:
      - /home/wesmd7/ml-workspace:/workspace
      - /home/dockeruser/shared-DVC-cache:/dvc-cache
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 800000000 # ~16gb
    environment:
      - AUTHENTICATE_VIA_JUPYTER=$IKEPWD 
    restart: always
  ml-workspace-aish:
    #build: .build
    image: chezhipower/ml-workspace-devenv1:0
    ports:
      - 8855:8080
    volumes:
      - /home/vanuc9/ml-workspace:/workspace
      - /home/dockeruser/shared-DVC-cache:/dvc-cache
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 800000000 # ~16gb
    environment:
      - AUTHENTICATE_VIA_JUPYTER=$AISHPWD 
    restart: always
  ml-workspace-madi:
    #build: .build
    image: chezhipower/ml-workspace-devenv1:0
    ports:
      - 8852:8080
    volumes:
      - /home/shaf9a/ml-workspace:/workspace
      - /home/dockeruser/shared-DVC-cache:/dvc-cache
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 800000000 # ~16gb
    environment:
      - AUTHENTICATE_VIA_JUPYTER=$MADIPWD 
    restart: always
  ml-workspace-neer:
    #build: .build
    image: chezhipower/ml-workspace-devenv1:0
    ports:
      - 8853:8080
      - 8003:8000
    volumes:
      - /home/mahfq2/ml-workspace:/workspace
      - /home/dockeruser/shared-DVC-cache:/dvc-cache
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 800000000 # ~16gb
    environment:
      - AUTHENTICATE_VIA_JUPYTER=$NEERPWD 
    restart: always
  ml-workspace-zach:
    #build: .build
    image: chezhipower/ml-workspace-devenv1:0
    ports:
      - 8854:8080
    volumes:
      - /home/tay4zt/ml-workspace:/workspace
      - /home/dockeruser/shared-DVC-cache:/dvc-cache
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 800000000 # ~16gb
    environment:
      - AUTHENTICATE_VIA_JUPYTER=$ZACHPWD 
    restart: always
volumes:
  minio_data_p:   # Cache Drive to SSD /data/minio/1
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/minio/production_cache
  minio_mnt_p:    # RDS6 Remote share, docker volume already created using create_docker_volume.sh
    external: true